global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'redis-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cache'
    scrape_interval: 2s
    static_configs:
      - targets: ['exporter:9121']