services:
  exporter:
    image: oliver006/redis_exporter:v1.67.0-alpine
    environment:
      - REDIS_PASSWORD=data_store_password
    ports:
      - 9121:9121
    command:
      - '--redis.addr=redis://datastore:6379'
  prometheus:
    image: prom/prometheus:v2.36.2
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    ports:
    - 9090:9090
    #links:
    #  - redis:redis
    volumes:
      - ./var/data/prometheus:/prometheus
      - ./var/prometheus/config:/etc/prometheus
  grafana:
      image: grafana/grafana:latest
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      volumes:
        - ./var/data/grafana:/var/lib/grafana
        - ./var/grafana/provisioning/:/etc/grafana/provisioning/
      env_file:
        - ./var/grafana/config.monitoring